/**
 * @module seed
 * 首次启动时写入初始管理员账户。
 * 密码取自 ADMIN_INITIAL_PASSWORD 环境变量；若未设置则随机生成并打印。
 * 若 admins 表已有记录则跳过（幂等）。
 */

import * as bcrypt from 'bcryptjs';
import { eq } from 'drizzle-orm';

import { createLogger } from '@dice-soup/logger';
import { admins } from './schema';
import { getDatabase } from './client';

const log = createLogger({ module: 'seed' });

export async function seedInitialAdmin(): Promise<void> {
  const db = getDatabase();

  // 获取初始密码（用于创建或同步）
  let password = process.env.ADMIN_INITIAL_PASSWORD?.trim();

  // 检查是否已有管理员
  const existing = db.select().from(admins).limit(1).all();
  if (existing.length > 0) {
    // 已有管理员；若环境变量中设置了密码，则同步（方便开发/运维重置）
    if (password) {
      const passwordHash = await bcrypt.hash(password, 12);
      db.update(admins)
        .set({ passwordHash, mustChangePw: 0 })
        .where(eq(admins.username, 'admin'))
        .run();
      log.info({ username: 'admin' }, '[seed] 已从 ADMIN_INITIAL_PASSWORD 同步管理员密码');
    } else {
      log.debug('[seed] admins 表已有记录，跳过 seed');
    }
    return;
  }
  let autoGenerated = false;

  if (!password) {
    // 随机生成 16 字符密码
    const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789!@#$%';
    password = Array.from({ length: 16 }, () => chars[Math.floor(Math.random() * chars.length)]).join('');
    autoGenerated = true;
  }

  const passwordHash = await bcrypt.hash(password, 12);
  const now = Math.floor(Date.now() / 1000);

  db.insert(admins)
    .values({
      username: 'admin',
      passwordHash,
      displayName: 'Administrator',
      createdAt: now,
      disabled: 0,
      mustChangePw: 1, // 首次登录必须改密码
    })
    .run();

  if (autoGenerated) {
    // 醒目打印，方便用户复制
    log.warn(
      { username: 'admin', password },
      '⚠️  ADMIN_INITIAL_PASSWORD not set — generated a random password. ' +
        'Please copy it NOW and log in to change it. ' +
        'You can then remove ADMIN_INITIAL_PASSWORD from your .env file.',
    );
    // 同时直接打印到 stdout，确保不被 pino 格式化丢失
    console.log('\n┌─────────────────────────────────────────────┐');
    console.log('│  Initial admin credentials (one-time only)  │');
    console.log('│                                             │');
    console.log(`│  Username : admin                           │`);
    console.log(`│  Password : ${password.padEnd(33)}│`);
    console.log('│                                             │');
    console.log('│  Log in and change the password ASAP.       │');
    console.log('└─────────────────────────────────────────────┘\n');
  } else {
    log.info({ username: 'admin' }, 'Initial admin account created from ADMIN_INITIAL_PASSWORD');
  }
}
