/**
 * @module game-common/errors
 * GAME_COMMON_* 错误码。
 */

export const GameCommonErrorCodes = {
  LOBBY_FULL: 'GAME_COMMON_LOBBY_FULL',
  LOBBY_NOT_OPEN: 'GAME_COMMON_LOBBY_NOT_OPEN',
  PLAYER_ALREADY_JOINED: 'GAME_COMMON_PLAYER_ALREADY_JOINED',
  PLAYER_NOT_IN_LOBBY: 'GAME_COMMON_PLAYER_NOT_IN_LOBBY',
  NOT_ENOUGH_PLAYERS: 'GAME_COMMON_NOT_ENOUGH_PLAYERS',
  TOO_MANY_PLAYERS: 'GAME_COMMON_TOO_MANY_PLAYERS',
  VOTE_ALREADY_ACTIVE: 'GAME_COMMON_VOTE_ALREADY_ACTIVE',
  VOTE_NOT_ACTIVE: 'GAME_COMMON_VOTE_NOT_ACTIVE',
  ALREADY_VOTED: 'GAME_COMMON_ALREADY_VOTED',
  CANNOT_KICK_CREATOR: 'GAME_COMMON_CANNOT_KICK_CREATOR',
  CANNOT_KICK_SELF: 'GAME_COMMON_CANNOT_KICK_SELF',
  VOTE_EXPIRED: 'GAME_COMMON_VOTE_EXPIRED',
} as const;

export type GameCommonErrorCode = (typeof GameCommonErrorCodes)[keyof typeof GameCommonErrorCodes];
